// src/workflows/execute-task.ts
import { type WorkflowEvent, type WorkflowStep, WorkflowEntrypoint } from "cloudflare:workers";

import type { RunRecord, StepStatus } from "@shipbox/shared";
import * as Sentry from "@sentry/cloudflare";
import { getErrorCategory } from "@shipbox/shared";
import { type WorkflowEvent as TelemetryEvent, WorkflowEventBuilder } from "../services/telemetry";
import {
  Backup,
  OpenCode,
  Run,
  Sandbox,
  type TaskParams,
  type TaskResult,
  type WorkflowDeps,
} from "./helpers";

/**
 * Workflow that executes OpenCode tasks durably inside Cloudflare Sandboxes.
 *
 * IMPORTANT: Workflow steps must return serializable values only.
 * Sandbox instances (DO stubs) are NOT serializable and must be
 * obtained fresh in each step that needs them.
 *
 * This is the core of the MCP server - it:
 * 1. Creates the run record in R2
 * 2. Ensures sandbox is ready (restore backup, clone repo, configure proxy)
 * 3. Starts OpenCode inside the sandbox and executes the task
 * 4. Gets the session title (auto-generated by OpenCode)
 * 5. Backs up session state
 * 6. Completes the run record in R2
 */
export class ExecuteTaskWorkflow extends WorkflowEntrypoint<Env, TaskParams> {
  /**
   * Initialize Sentry for the workflow instance
   */
  private initSentry(params: TaskParams, instanceId: string) {
    if (this.env.SENTRY_DSN) {
      Sentry.setTag("workflowId", instanceId);
      Sentry.setTag("requestId", params.requestId);
      Sentry.setTag("runId", params.runId);
      Sentry.setTag("sessionId", params.sessionId);
      Sentry.setTag("userId", params.userId);
    }
  }

  /**
   * Build workflow dependencies from env.
   *
   * Note: No secrets here - all authentication is handled by the proxy
   * using JWT tokens passed in TaskParams.
   */
  private getDeps(): WorkflowDeps {
    return {
      sandboxBinding: this.env.Sandbox,
      sessionsBucket: this.env.SESSIONS_BUCKET,
    };
  }

  /**
   * Update the status of a specific workflow step in R2.
   */
  private async updateStep(
    runId: string,
    stepName: string,
    status: StepStatus,
    durationMs?: number,
    error?: string,
  ) {
    try {
      await Run.updateRunStep(this.env.SESSIONS_BUCKET, runId, stepName, status, durationMs, error);

      // Write to Analytics Engine if duration is provided (step completed or failed)
      if (durationMs !== undefined && this.env.METRICS) {
        this.env.METRICS.writeDataPoint({
          blobs: [stepName, status, this.env.ENVIRONMENT || "production"],
          doubles: [durationMs],
          indexes: [runId], // Use runId as index for correlation
        });
      }
    } catch (err) {
      // Don't fail the workflow if status update fails
      console.error(`Failed to update step status for ${stepName}: ${err}`);
    }
  }

  async run(event: WorkflowEvent<TaskParams>, step: WorkflowStep): Promise<TaskResult> {
    const params = event.payload;
    const deps = this.getDeps();

    this.initSentry(params, event.instanceId);

    // Create telemetry event builder
    // Constructor: (workflowId, requestId, runId, sessionId)
    const telemetry = new WorkflowEventBuilder(
      event.instanceId, // workflowId - the workflow instance ID
      params.requestId, // requestId - correlation ID from API
      params.runId, // runId - our run tracking ID
      params.sessionId, // sessionId
    );

    let currentPhase = "initialization";

    try {
      // Step 0: Pre-flight balance check
      currentPhase = "check-balance";
      telemetry.startPhase(currentPhase);
      await this.updateStep(params.runId, currentPhase, "running");
      await step.do("check-balance", async () => {
        return await Sentry.withScope(async (scope) => {
          scope.setTag("step", "check-balance");
          Sentry.addBreadcrumb({
            category: "workflow",
            message: "Checking balance",
            level: "info",
          });

          const balanceRes = await this.env.SHIPBOX_API.fetch(
            `http://api/internal/check-balance/${params.userId}`,
          );
          if (!balanceRes.ok) {
            const errorData = (await balanceRes.json()) as any;
            throw new Error(errorData.error || "Insufficient balance");
          }
          return { ok: true };
        });
      });
      telemetry.endPhase("check-balance");
      await this.updateStep(
        params.runId,
        "check-balance",
        "completed",
        telemetry.finalize().phases?.["check-balance"],
      );

      // Step 1: Create run record in R2 (doesn't need sandbox)
      currentPhase = "create-run";
      telemetry.startPhase(currentPhase);
      await this.updateStep(params.runId, currentPhase, "running");
      await step.do("create-run", async () => {
        return await Sentry.withScope(async (scope) => {
          scope.setTag("step", "create-run");
          Sentry.addBreadcrumb({
            category: "workflow",
            message: "Creating run record",
            level: "info",
          });
          const run: RunRecord = {
            runId: params.runId,
            sessionId: params.sessionId,
            workflowId: event.instanceId,
            status: "started",
            task: params.task,
            title: params.title,
            model: params.model,
            startedAt: Date.now(),
          };
          await Run.createRun(deps.sessionsBucket, run);
          return { created: true };
        });
      });
      telemetry.endPhase("create-run");
      await this.updateStep(
        params.runId,
        "create-run",
        "completed",
        telemetry.finalize().phases?.["create-run"],
      );

      // Step 2: Ensure sandbox is ready (restore backup, clone repo, configure proxy)
      // This is idempotent - safe to retry if workflow step fails
      currentPhase = "ensure-sandbox-ready";
      telemetry.startPhase(currentPhase);
      await this.updateStep(params.runId, currentPhase, "running");
      const sandboxResult = await step.do("ensure-sandbox-ready", async () => {
        return await Sentry.withScope(async (scope) => {
          scope.setTag("step", "ensure-sandbox-ready");
          Sentry.addBreadcrumb({
            category: "workflow",
            message: "Ensuring sandbox ready",
            level: "info",
            data: { repository: params.repositoryUrl },
          });
          const sandbox = Sandbox.getSandbox(deps, params.sandboxId);
          const result = await Sandbox.ensureSandboxReady({
            sandbox,
            sessionId: params.sessionId,
            bucket: deps.sessionsBucket,
            proxyBaseUrl: params.proxyBaseUrl,
            proxyToken: params.proxyToken,
            repository: params.repositoryUrl
              ? { url: params.repositoryUrl, branch: params.branch }
              : undefined,
          });
          return result;
        });
      });
      telemetry.endPhase("ensure-sandbox-ready");
      await this.updateStep(
        params.runId,
        "ensure-sandbox-ready",
        "completed",
        telemetry.finalize().phases?.["ensure-sandbox-ready"],
      );
      telemetry.setMetadata({ sessionRestored: sandboxResult.restoredBackup });

      const workingDirectory = sandboxResult.workspacePath;

      // Step 2.5: Update session with workspace path immediately for web UI access
      currentPhase = "update-workspace-path";
      telemetry.startPhase(currentPhase);
      await this.updateStep(params.runId, currentPhase, "running");
      await step.do("update-workspace-path", async () => {
        return await Sentry.withScope(async (scope) => {
          scope.setTag("step", "update-workspace-path");
          Sentry.addBreadcrumb({
            category: "workflow",
            message: "Updating workspace path",
            level: "info",
            data: { workingDirectory },
          });
          await Run.updateSessionAfterRun(deps.sessionsBucket, params.sessionId, {
            workspacePath: workingDirectory,
          });
          return { updated: true };
        });
      });
      telemetry.endPhase("update-workspace-path");
      await this.updateStep(
        params.runId,
        "update-workspace-path",
        "completed",
        telemetry.finalize().phases?.["update-workspace-path"],
      );

      // Step 3: Start OpenCode and execute task
      currentPhase = "execute-opencode-task";
      telemetry.startPhase(currentPhase);
      await this.updateStep(params.runId, currentPhase, "running");
      const executeResult = await step.do(
        "execute-opencode-task",
        {
          retries: {
            limit: 3,
            delay: "10 seconds",
            backoff: "exponential",
          },
          timeout: "50 minutes",
        },
        async () => {
          return await Sentry.withScope(async (scope) => {
            scope.setTag("step", "execute-opencode-task");
            Sentry.addBreadcrumb({
              category: "workflow",
              message: "Executing OpenCode task",
              level: "info",
              data: { task: params.task },
            });
            const sandbox = Sandbox.getSandbox(deps, params.sandboxId);
            return OpenCode.executeTask(sandbox, params, workingDirectory);
          });
        },
      );
      telemetry.endPhase("execute-opencode-task");
      await this.updateStep(
        params.runId,
        "execute-opencode-task",
        "completed",
        telemetry.finalize().phases?.["execute-opencode-task"],
      );

      // Step 4: Get session title (auto-generated by OpenCode)
      currentPhase = "get-session-title";
      telemetry.startPhase(currentPhase);
      await this.updateStep(params.runId, currentPhase, "running");
      const title = await step.do("get-session-title", async () => {
        return await Sentry.withScope(async (scope) => {
          scope.setTag("step", "get-session-title");
          Sentry.addBreadcrumb({
            category: "workflow",
            message: "Getting session title",
            level: "info",
          });
          const sandbox = Sandbox.getSandbox(deps, params.sandboxId);
          return OpenCode.getSessionTitle(
            sandbox,
            executeResult.opencodeSessionId,
            params.proxyBaseUrl,
            params.proxyToken,
            workingDirectory,
          );
        });
      });
      telemetry.endPhase("get-session-title");
      await this.updateStep(
        params.runId,
        "get-session-title",
        "completed",
        telemetry.finalize().phases?.["get-session-title"],
      );

      // Step 5: Backup session state to R2
      currentPhase = "backup-session";
      telemetry.startPhase(currentPhase);
      await this.updateStep(params.runId, currentPhase, "running");
      await step.do("backup-session", async () => {
        return await Sentry.withScope(async (scope) => {
          scope.setTag("step", "backup-session");
          Sentry.addBreadcrumb({
            category: "workflow",
            message: "Backing up session",
            level: "info",
          });
          const sandbox = Sandbox.getSandbox(deps, params.sandboxId);
          await Backup.backupSession(sandbox, params.sessionId, deps.sessionsBucket);
          return { backedUp: true };
        });
      });
      telemetry.endPhase("backup-session");
      await this.updateStep(
        params.runId,
        "backup-session",
        "completed",
        telemetry.finalize().phases?.["backup-session"],
      );

      const result: TaskResult = {
        success: executeResult.result.success,
        output: executeResult.result.output,
        error: executeResult.result.error,
        title,
        opencodeSessionId: executeResult.opencodeSessionId,
        workspacePath: workingDirectory,
        tokens: executeResult.result.tokens,
      };

      // Step 6: Complete run and update session in R2
      currentPhase = "complete-run";
      telemetry.startPhase(currentPhase);
      await this.updateStep(params.runId, currentPhase, "running");
      await step.do("complete-run", async () => {
        return await Sentry.withScope(async (scope) => {
          scope.setTag("step", "complete-run");
          await Run.completeRun(deps.sessionsBucket, params.runId, {
            success: result.success,
            output: result.output,
            error: result.error,
            title: result.title,
          });

          if (result.opencodeSessionId || result.workspacePath) {
            await Run.updateSessionAfterRun(deps.sessionsBucket, params.sessionId, {
              opencodeSessionId: result.opencodeSessionId,
              workspacePath: result.workspacePath,
            });
          }

          return { completed: true };
        });
      });
      telemetry.endPhase("complete-run");
      await this.updateStep(
        params.runId,
        "complete-run",
        "completed",
        telemetry.finalize().phases?.["complete-run"],
      );

      // Emit success telemetry
      telemetry.setOutcome("success");
      this.emitTelemetry(telemetry.finalize());

      return result;
    } catch (error) {
      const category = getErrorCategory(error);

      // Record error in Sentry
      Sentry.captureException(error, {
        tags: { category },
        extra: { workflowId: event.instanceId, runId: params.runId, sessionId: params.sessionId },
      });

      // Record error in telemetry
      const errorName = error instanceof Error ? error.name : "UnknownError";
      const errorMessage = error instanceof Error ? error.message : String(error);

      // Update the failing step status in R2
      await this.updateStep(params.runId, currentPhase, "failed", undefined, errorMessage);

      telemetry.setError({
        type: errorName,
        code: errorName,
        message: errorMessage,
        phase: currentPhase,
        retriable: category.startsWith("system"),
      });
      telemetry.setMetadata({ category });
      this.emitTelemetry(telemetry.finalize());

      // Handle errors and still complete the run
      const errorResult: TaskResult = {
        success: false,
        error: error instanceof Error ? error.message : String(error),
      };

      await step.do("complete-run-failure", async () => {
        await Run.completeRun(deps.sessionsBucket, params.runId, {
          success: false,
          error: errorResult.error,
        });
        return { completed: true };
      });

      return errorResult;
    }
  }

  /**
   * Emit telemetry event as wide event log line
   */
  private emitTelemetry(event: TelemetryEvent): void {
    console.log(
      JSON.stringify({
        level: event.error ? "error" : "info",
        type: "workflow.event",
        ...event,
      }),
    );
  }
}
