// src/workflows/execute-task.ts
import { WorkflowEntrypoint, type WorkflowEvent, type WorkflowStep } from "cloudflare:workers";

import { WorkflowEventBuilder, type WorkflowEvent as TelemetryEvent } from "../services/telemetry";
import {
  Backup,
  type McpAgentStub,
  OpenCode,
  Sandbox,
  type TaskParams,
  type TaskResult,
  type WorkflowDeps,
} from "./helpers";

/**
 * Workflow that executes OpenCode tasks durably inside Cloudflare Sandboxes.
 *
 * IMPORTANT: Workflow steps must return serializable values only.
 * Sandbox instances (DO stubs) are NOT serializable and must be
 * obtained fresh in each step that needs them.
 *
 * This is the core of the MCP server - it:
 * 1. Mounts R2 storage for persistence
 * 2. Restores any previous session state
 * 3. Clones the repository if needed
 * 4. Starts OpenCode inside the sandbox
 * 5. Executes the task via the OpenCode SDK
 * 6. Gets the session title (auto-generated by OpenCode)
 * 7. Backs up session state
 * 8. Notifies the DO of completion via RPC
 */
export class ExecuteTaskWorkflow extends WorkflowEntrypoint<Env, TaskParams> {
  /**
   * Build workflow dependencies from env.
   *
   * Note: No secrets here - all authentication is handled by the proxy
   * using JWT tokens passed in TaskParams.
   */
  private getDeps(): WorkflowDeps {
    return {
      sandboxBinding: this.env.Sandbox,
      mcpAgentBinding: this.env.MCP_AGENT,
      sessionsBucket: this.env.SESSIONS_BUCKET,
    };
  }

  async run(event: WorkflowEvent<TaskParams>, step: WorkflowStep): Promise<TaskResult> {
    const params = event.payload;
    const deps = this.getDeps();

    // Create telemetry event builder
    // Constructor: (workflowId, runId, sessionId)
    const telemetry = new WorkflowEventBuilder(
      event.instanceId, // workflowId - the workflow instance ID
      params.runId, // runId - our run tracking ID
      params.sessionId, // sessionId
    );

    try {
      // Step 1: Configure sandbox to use proxy for all external services
      // This sets up Anthropic SDK and git to route through our zero-trust proxy
      await step.do("configure-proxy", async () => {
        const sandbox = Sandbox.getSandbox(deps, params.sandboxId);
        await Sandbox.configureSandboxProxy(sandbox, params.proxyBaseUrl, params.proxyToken);
        await Sandbox.setupGitConfig(sandbox);
        return { configured: true };
      });

      // Step 2: Mount R2 storage for workspace persistence (via proxy)
      await step.do("mount-storage", async () => {
        const sandbox = Sandbox.getSandbox(deps, params.sandboxId);
        await Sandbox.mountR2Storage(
          sandbox,
          params.sessionId,
          params.proxyBaseUrl,
          params.proxyToken,
        );
        return { mounted: true };
      });

      // Step 3: Restore OpenCode session state from backup
      const restoreResult = await step.do("restore-session", async () => {
        const sandbox = Sandbox.getSandbox(deps, params.sandboxId);
        const restored = await Backup.restoreSession(
          sandbox,
          params.sessionId,
          deps.sessionsBucket,
        );
        return { restored };
      });
      telemetry.setMetadata({ sessionRestored: restoreResult.restored });

      // Step 4: Clone repository if needed (git uses proxy for auth)
      // Returns the working directory where the repo was cloned
      let workingDirectory = "/workspace";
      if (params.repositoryUrl) {
        const cloneResult = await step.do("clone-repository", async () => {
          const sandbox = Sandbox.getSandbox(deps, params.sandboxId);
          const targetDir = await Sandbox.cloneRepository(
            sandbox,
            params.repositoryUrl!,
            params.branch,
          );
          return { cloned: true, targetDir };
        });
        workingDirectory = cloneResult.targetDir;
      }

      // Step 5: Start OpenCode and execute task
      const executeResult = await step.do(
        "execute-opencode-task",
        {
          retries: {
            limit: 3,
            delay: "10 seconds",
            backoff: "exponential",
          },
          timeout: "50 minutes",
        },
        async () => {
          const sandbox = Sandbox.getSandbox(deps, params.sandboxId);
          return OpenCode.executeTask(sandbox, params, workingDirectory);
        },
      );

      // Step 6: Get session title (auto-generated by OpenCode)
      const title = await step.do("get-session-title", async () => {
        const sandbox = Sandbox.getSandbox(deps, params.sandboxId);
        return OpenCode.getSessionTitle(
          sandbox,
          executeResult.opencodeSessionId,
          params.proxyBaseUrl,
          params.proxyToken,
          workingDirectory,
        );
      });

      // Step 7: Backup session state to R2
      await step.do("backup-session", async () => {
        const sandbox = Sandbox.getSandbox(deps, params.sandboxId);
        await Backup.backupSession(sandbox, params.sessionId, deps.sessionsBucket);
        return { backedUp: true };
      });

      const result: TaskResult = {
        success: executeResult.result.success,
        output: executeResult.result.output,
        error: executeResult.result.error,
        title,
        opencodeSessionId: executeResult.opencodeSessionId,
        workspacePath: workingDirectory,
        tokens: executeResult.result.tokens,
      };

      // Step 8: Notify DO via RPC callback
      await step.do("notify-completion", async () => {
        await this.notifyCompletion(deps, params.doId, params.runId, result);
        return { notified: true };
      });

      // Emit success telemetry
      telemetry.setOutcome("success");
      this.emitTelemetry(telemetry.finalize());

      return result;
    } catch (error) {
      // Record error in telemetry
      const errorName = error instanceof Error ? error.name : "UnknownError";
      const errorMessage = error instanceof Error ? error.message : String(error);
      telemetry.setError({
        type: errorName,
        code: errorName,
        message: errorMessage,
        phase: "execution",
        retriable: true,
      });
      this.emitTelemetry(telemetry.finalize());

      // Handle errors and still notify DO
      const errorResult: TaskResult = {
        success: false,
        error: error instanceof Error ? error.message : String(error),
      };

      await step.do("notify-failure", async () => {
        await this.notifyCompletion(deps, params.doId, params.runId, errorResult);
        return { notified: true };
      });

      return errorResult;
    }
  }

  /**
   * Emit telemetry event as wide event log line
   */
  private emitTelemetry(event: TelemetryEvent): void {
    console.log(
      JSON.stringify({
        level: event.error ? "error" : "info",
        type: "workflow.event",
        ...event,
      }),
    );
  }

  /**
   * Notify the MCP Agent DO of task completion via RPC
   */
  private async notifyCompletion(
    deps: WorkflowDeps,
    doId: string,
    runId: string,
    result: TaskResult,
  ): Promise<void> {
    // Use unknown binding to avoid TypeScript infinite type instantiation
    const binding = deps.mcpAgentBinding as unknown as DurableObjectNamespace;
    const doIdObj = binding.idFromString(doId);
    const stub = binding.get(doIdObj) as unknown as McpAgentStub;

    await stub.onTaskComplete({
      runId,
      result,
    });
  }
}
