// Generated by Wrangler by running `wrangler types`

interface Env {
	ENVIRONMENT: "development";
	MCP_AGENT: DurableObjectNamespace /* OpenCodeMcpAgent */;
	SESSIONS_BUCKET: R2Bucket;
	EXECUTE_TASK_WORKFLOW: Workflow;
}
