// Generated by Wrangler by running `wrangler types`
// Extended with Sandbox binding and secrets

import type { Sandbox } from "@cloudflare/sandbox";

declare global {
	interface Env {
		// Environment
		ENVIRONMENT: "development" | "production";

		// Durable Object bindings
		MCP_AGENT: DurableObjectNamespace<import("./src/index").OpenCodeMcpAgent>;

		// Sandbox binding - Cloudflare Containers/Sandbox infrastructure
		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		SANDBOX: DurableObjectNamespace<Sandbox<any>>;

		// R2 bucket for session persistence
		SESSIONS_BUCKET: R2Bucket;

		// Workflow binding
		EXECUTE_TASK_WORKFLOW: Workflow;

		// Secrets (set via wrangler secret put)
		R2_ACCOUNT_ID: string;
		R2_ACCESS_KEY_ID: string;
		R2_SECRET_ACCESS_KEY: string;
		ANTHROPIC_API_KEY: string;
		GITHUB_TOKEN?: string;
	}
}

export {};
